accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('profile/', views.profile, name="profile")
]

mainapp/urls.py
from django.urls import path

from . import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.index_view, name='index'),
    path('leaderboard', views.leaderboard_view, name='leaderboard'),
    path('personal_stats/', views.personal_stats_view, name='personal_stats'),
    path('progress', views.progress_view, name='progress'),
    path('progress_versus', views.progress_versus_view, name='progress_versus'),
    path('feedback', views.feedback_view, name='feedback'),
    path('best_message', views.best_message_view, name='best_message')
]

message_stat_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('mainapp.urls', namespace='mainapp')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts'))
]

mainapp/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class FeedbackModel(models.Model):
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    body = models.TextField(verbose_name='', default='write your feedback here...')

    def snippet(self):
        return self.body[:30] + '...'

    def __str__(self):
        return self.snippet()

mainapp/forms.py
from django import forms
import datetime
from . import models
from django.contrib.auth.models import User
from .core import common_functions


class LeaderBoardForm(forms.Form):
    start_date = forms.DateField(initial=datetime.date(2000, 1, 30).strftime("%d/%m/%Y"),
                                 input_formats=['%d/%m/%Y'],
                                 label="Start date ",
                                 widget=forms.TextInput(attrs={
                                     'placeholder': '30/01/2000',
                                     'class': 'formEntry dateEntry'})
                                 )
    end_date = forms.DateField(initial=datetime.date(2023, 1, 30).strftime("%d/%m/%Y"),
                               input_formats=['%d/%m/%Y'],
                               label="End date ",
                               widget=forms.TextInput(attrs={
                                   'placeholder': '30/01/2023',
                                   'class': 'formEntry dateEntry'})
                               )

    top_best = forms.IntegerField(min_value=1,
                                  required=False,
                                  widget=forms.TextInput(attrs={
                                      'class': 'formEntry integerEntry'}),
                                  label="See only x best "
                                  )

    top_worst = forms.IntegerField(min_value=1,
                                   required=False,
                                   widget=forms.TextInput(attrs={
                                       'class': 'formEntry integerEntry'}),
                                   label="See only x worst "
                                   )

    graph_type = forms.ChoiceField(choices=[('number', 'Message count'), ('avg length', 'Average message length'),
                                            ('total chars', 'Total characters')],
                                   label="Value compared ",
                                   widget=forms.Select(attrs={
                                       'class': 'formEntry dateEntry'})
                                   )


class PersonalStatsForm(forms.Form):
    names = common_functions.get_all_names()
    name = forms.ChoiceField(choices=[(n, n) for n in names],
                             label="Nom ",
                             widget=forms.Select(attrs={
                                 'class': 'formEntry dateEntry'})
                             )
    start_date = forms.DateField(initial=datetime.date(2000, 1, 30).strftime("%d/%m/%Y"),
                                 input_formats=['%d/%m/%Y'],
                                 label="Start date ",
                                 widget=forms.TextInput(attrs={
                                     'placeholder': '30/01/2000',
                                     'class': 'formEntry dateEntry'})
                                 )
    end_date = forms.DateField(initial=datetime.date(2023, 1, 30).strftime("%d/%m/%Y"),
                               input_formats=['%d/%m/%Y'],
                               label="End date ",
                               widget=forms.TextInput(attrs={
                                   'placeholder': '30/01/2023',
                                   'class': 'formEntry dateEntry'})
                               )
    word = forms.CharField(initial='hello', label='Word Search')


class ProgressForm(forms.Form):
    names = common_functions.get_all_names()
    names.append('all')
    name = forms.ChoiceField(choices=[(n, n) for n in names],
                             label="Nom ",
                             widget=forms.Select(attrs={
                                 'class': 'formEntry dateEntry'})
                             )

    mode = forms.ChoiceField(choices=[('per', 'change per month'), ('total', 'total messages at month')])

    graph_type = forms.ChoiceField(choices=[('bar', 'bar'), ('curve', 'curve')])


class ProgressFormVersus(forms.Form):
    names_list = common_functions.get_all_names()
    names = forms.MultipleChoiceField(choices=[(n, n) for n in names_list],
                                      label="Names to compare : (ctrl + click)"
                                      )


class BestMessageForm(forms.Form):
    react_list = ['❤', '😆', '👍', '😮', '😂', '👎', '🤡', '🗿', 'all']

    react = forms.ChoiceField(choices=[(n, n) for n in react_list])
    n_msg = forms.IntegerField(initial=1, min_value=1, max_value=100, label='Top : ')


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = models.FeedbackModel
        fields = ['body']

mainapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .core import leaderboard_functions, personal_stats_functions, progress_functions, common_functions
from django.shortcuts import redirect
from .forms import LeaderBoardForm, PersonalStatsForm, ProgressForm, ProgressFormVersus, BestMessageForm, FeedbackForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import user_passes_test


def group_required(*group_names):
    """View decorator : requires user membership in at least one of the groups passed in."""
    def in_groups(u):
        if u.is_authenticated:
            if bool(u.groups.filter(name__in=group_names)) | u.is_superuser:
                return True
        return False

    return user_passes_test(in_groups)


def index_view(request):
    template = loader.get_template('index.html')
    leaderboard = common_functions.refactor_dict(leaderboard_functions.get_leader_board())
    names = list(leaderboard.keys())
    top1, top2, top3 = names[0], names[1], names[2]
    return HttpResponse(template.render({'top1': top1, 'top2': top2, 'top3': top3}, request))


def leaderboard_view(request):
    if request.method == 'POST':

        form = LeaderBoardForm(request.POST)
        start_date = request.POST['start_date']
        end_date = request.POST['end_date']

        top_best = request.POST['top_best']
        top_worst = request.POST['top_worst']
        graph_type = request.POST['graph_type']

        b64 = leaderboard_functions.get_leader_board_image(str(start_date), str(end_date),
                                                           top_best, top_worst, graph_type)
        template = loader.get_template('leaderboard_post.html')
        return HttpResponse(template.render({'chart': b64, 'form': form}, request))
    else:
        template = loader.get_template('leaderboard.html')
        return HttpResponse(template.render({'form': LeaderBoardForm()}, request))


def personal_stats_view(request):
    if request.method == 'POST':
        form = PersonalStatsForm(request.POST)
        start_date = request.POST['start_date']
        end_date = request.POST['end_date']
        name = request.POST['name']
        word = request.POST['word']

        context = personal_stats_functions.get_personal_stats(name, start_date, end_date, word)
        context = context | {'name': name, 'form': form, 'start_date': start_date, 'end_date': end_date, 'word': word}
        context['name'] = name
        context['form'] = form
        template = loader.get_template('personal_stats_post.html')
        return HttpResponse(template.render(context, request))
    else:
        template = loader.get_template('personal_stats.html')
        return HttpResponse(template.render({'form': PersonalStatsForm()}, request))


def progress_view(request):
    if request.method == 'POST':
        form = ProgressForm(request.POST)
        name = request.POST['name']
        mode = request.POST['mode']
        graph_type = request.POST['graph_type']

        b64 = progress_functions.get_image_progress(name, mode, graph_type)
        context = {'chart': b64, 'form': form}
        template = loader.get_template('progress_post.html')
        return HttpResponse(template.render(context, request))
    else:
        template = loader.get_template('progress.html')
        return HttpResponse(template.render({'form': ProgressForm()}, request))


def progress_versus_view(request):
    if request.method == 'POST':
        form = ProgressFormVersus(request.POST)
        if form.is_valid():
            names = form.cleaned_data.get('names')
            b64 = progress_functions.get_image_progress_versus(names)
            context = {'chart': b64, 'form': form}
            template = loader.get_template('progress_versus_post.html')
            return HttpResponse(template.render(context, request))
    else:
        template = loader.get_template('progress_versus.html')
        return HttpResponse(template.render({'form': ProgressFormVersus()}, request))


@login_required()
def feedback_view(request):  # any user can send feedback : use signup form to create account
    if request.method == 'POST':
        form = FeedbackForm(request.POST, request.FILES)
        if form.is_valid():
            # save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('mainapp:feedback')
    else:
        form = FeedbackForm()
    return render(request, 'feedback.html', {'form': form})


@group_required('see-messages-auth')
def best_message_view(request):  # must have special permissions, this page will reveal messages
    if request.method == 'POST':
        form = BestMessageForm(request.POST)
        react = request.POST['react']
        n_msg = int(request.POST['n_msg'])
        top_list = progress_functions.get_best_messages(react, n=n_msg)
        context = {'top_list': top_list, 'form': form}
        template = loader.get_template('best_message_post.html')
        return HttpResponse(template.render(context, request))
    else:
        template = loader.get_template('best_message.html')
        return HttpResponse(template.render({'form': BestMessageForm()}, request))

mainapp/templates/base_template.html
<!DOCTYPE html>
{% load static %}
<link rel="stylesheet" href="{% static 'style.css' %}">
<link rel="stylesheet" href="{% static 'properties.css' %}">

<html lang="fr">
<head>
	<meta charset="UTF-8">
	<title>Messenger Stats</title>
</head>
<body>
	<div class="wrapper">
			<div class="navbar">
				<!-- <img class="logo" src="{% static 'images/logo.png' %}" alt="My image"> -->
				<label class="logo">Messenger Stats</label>
				<ul>
					<li><a href="/">Home</a></li>
					<li><a href="{% url 'mainapp:leaderboard' %}">Leaderboard</a></li>
					<li><a href="{% url 'mainapp:personal_stats' %}">Personal Stats</a></li>
					<li><a href="{% url 'mainapp:progress' %}">Progress</a></li>
					<li><a href="{% url 'mainapp:progress_versus' %}">Compare Progress</a></li>
					<li><a href="{% url 'mainapp:best_message' %}">Best Messages</a></li>
					<li><a href="{% url 'mainapp:feedback' %}">Feedback</a></li>
					<!-- <li><a href="#">Contact</a></li> -->
					<!-- <li><a href="#">Feedback</a></li> -->

					{% if user.is_authenticated %}
                    <li><a href="{% url 'accounts:profile' %}" class="highlight">Profil</a></li>
					<li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}

				</ul>
			</div>

		<div class="center">
        {% block content %}{% endblock content %}
    	</div>
	</div>
</body>
</html>

mainapp/templates/best_message.html
{% extends "base_template.html" %}

{% block content %}
<div class="row">
    <div class="formContainer">
        <form action="/best_message" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Submit" class="submitbutton">
        </form>
    </div>
    {% block response %}{% endblock response %}
</div>
{% endblock content %}

mainapp/templates/best_message_post.html
{% extends "best_message.html" %}

{% block response %}
<dl>
  {% for message in top_list %}
    <dt>{{ message.sender }} - {{ message.date }} </dt>
    <dd class="details">
      {{ message.message }}
    </dd>
      <dt>Reacts : </dt>
    <dd class="details">
      {{ message.reactions }}
    </dd><br>
{% endfor %}
</dl>
{% endblock response %}

mainapp/templates/feedback.html
{% extends "base_template.html" %}

{% block content %}
<div class="row">

<div class="formContainer">
    <form action="{% url 'mainapp:feedback' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit" class="submitbutton">
    </form>
</div>
</div>
{% endblock content %}

mainapp/templates/index.html
{% extends "base_template.html" %}

{% block content %}
<div class="row">
    <div class="center">
        <h1>Top Active Group Chat members</h1>
        <div class="DIVpodium">
          <svg width="290" height="100" xmlns="http://www.w3.org/2000/svg" class="SVGpodium">
             <rect stroke="#000" stroke-width="3" id="svg_1" height="85" width="90" y="5" x="100" fill="#fff"/>
             <rect stroke="#000" stroke-width="3" id="svg_2" height="55" width="90" y="35" x="10" fill="#fff"/>
             <rect stroke="#000" stroke-width="3" id="svg_3" height="35" width="90" y="55" x="190" fill="#fff"/>
          </svg>
          <p class="Mediallepodium N1podium">&#129351</p>
          <p class="Mediallepodium N2podium">&#129352</p>
          <p class="Mediallepodium N3podium">&#129353</p>

          <p class="Nompodium N1Ppodium">{{ top1 }}</p>
          <p class="Nompodium N2Ppodium">{{ top2 }}</p>
          <p class="Nompodium N3Ppodium">{{ top3 }}</p>
        </div>

    </div>
</div>

{% endblock content %}

mainapp/templates/leaderboard.html
{% extends "base_template.html" %}

{% block content %}
<div class="row">
<div class="formContainer">
    <form action="{% url 'mainapp:leaderboard' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Submit" class="submitbutton">
    </form>
</div>
{% block image %}{% endblock image %}
</div>
{% endblock content %}

mainapp/templates/leaderboard_post.html
{% extends "leaderboard.html" %}

{% block image %}

<div class="imageResultat">
    <img src='data:image/png;base64,{{ chart }}' alt="Graphe">
</div>
{% endblock image %}

mainapp/templates/personal_stats.html
{% extends "base_template.html" %}

{% block content %}
<div class="row">
    <div class="formContainer">
        <form action="{% url 'mainapp:personal_stats' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Submit" class="submitbutton">
        </form>
    </div>
    <div class="formResponse">
    {% block response %}{% endblock response %}
    </div>
</div>
{% endblock content %}

mainapp/templates/personal_stats_post.html
{% extends "personal_stats.html" %}

{% block response %}
<h3>{{ name }}'s stats From {{ start_date }} to {{ end_date}}</h3>
<dl>
  <dt>Total messages sent</dt>
  <dd>-{{ message_count }}</dd><br>
  <dt>Total characters sent</dt>
  <dd>- {{ character_count }}</dd><br>
  <dt>Average message length </dt>
  <dd>- {{ average_message_length }}</dd><br>
  <dt>Number of times expression "{{ word }}" has been used</dt>
  <dd>- {{ word_count }}</dd><br>
</dl>
<details>
  <summary>Details for Reacts</summary>
  <dl>
  <dt>Received Reacts</dt>
  <dd>
    {% for key, value in received_emoji_count_dict.items %}
    {{key}} - {{value}} |
    {% endfor %}
    Total : {{ total_received }}
  </dd><br>
  <dt>Distributed Reacts</dt>
  <dd>
    {% for key, value in distributed_emoji_count_dict.items %}
    {{key}} - {{value}} |
    {% endfor %}
    Total : {{ total_distributed }}
  </dd><br>
  </dl>
</details>
<details>
  <summary>User details for reacts </summary>
  <dl>
  <dt>Users who sent {{ name }} reacts</dt>
  <dd class="dark-grey">
    <b>
    {% for key, value in received_emoji_name_dict.items %}
    {{key}} - {{value}} |
    {% endfor %}
    </b>
  </dd><br>
    <dt>Users who received reacts from {{ name }}</dt>
  <dd class="dark-grey"> <b>
    {% for key, value in distributed_emoji_name_dict.items %}
    {{key}} - {{value}} |
    {% endfor %}
    </b>
  </dd><br>
  </dl>
</details>
{% endblock response %}

mainapp/templates/progress.html
{% extends "base_template.html" %}

{% block content %}
<div class="row">
    <div class="formContainer">
        <form action="/progress" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Submit" class="submitbutton">
        </form>
    </div>
    {% block response %}{% endblock response %}
</div>
{% endblock content %}

mainapp/templates/progress_post.html
{% extends "progress.html" %}

{% block response %}
<div class="imageResultat">
    <img src='data:image/png;base64,{{ chart }}' alt="Graphe">
</div>
{% endblock response %}

mainapp/templates/progress_versus.html
{% extends "base_template.html" %}

{% block content %}
<div class="row">
    <div class="formContainer">
        <form action="{% url 'mainapp:progress_versus' %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Submit" class="submitbutton">
        </form>
    </div>
    {% block response %}{% endblock response %}
</div>
{% endblock content %}

mainapp/templates/progress_versus_post.html
{% extends "progress_versus.html" %}

{% block response %}
<div class="imageResultat">
    <img src='data:image/png;base64,{{ chart }}' alt="Graphe">
</div>
{% endblock response %}